# Theme Github link: https://github.com/argvchs/hexo-theme-particlex
# Developer: argvchs

# avatar image url 头像图片
head_img: https://cdn.jsdelivr.net/gh/GuoShuaiGO/Image_Shack_BLOG@main/img/QQ%E5%9B%BE%E7%89%8720230101095724.jpg

# home page head info block
head_block_enable: true

# home page head background style 背景图片
home_background: https://cdn.jsdelivr.net/gh/GuoShuaiGO/Image_Shack_BLOG@main/img/wallhaven.png

# WARNING! vf_fonts (variable fonts) feature is EXPERIMENTAL
# MDN: https://developer.mozilla.org/zh-CN/docs/Web/CSS/CSS_Fonts/Variable_Fonts_Guide
vf_fonts_enable: false

# ParticleX theme icon is adopts the font awesome 6
# Link: https://fontawesome.com/search/

# main menu navigation
menu:
    home:
        name: house
        theme: solid
        src: /
    about:
        name: id-card
        theme: solid
        src: /about
    archives:
        name: box-archive
        theme: solid
        src: /archives
    categories:
        name: bookmark
        theme: solid
        src: /categories
    tags:
        name: tags
        theme: solid
        src: /tags
    # Example:
    # <name>:
    #     name: <icon-name>
    #     theme: <icon-theme>
    #     src: <link-url>

# side info card
card:
    enable: true
    description: ["这是一个供tobey写学习，生活方面感想的blog树洞，主要是为了自娱自乐\n 别问有没有技术含量，问就是没有，问就全是ctrl+cv"] # You can add more
    icon_links:
        []
        # Example:
        # <name>:
        #    name: <icon-name>
        #    theme: <icon-theme>
        #    link: <link-url>
    friend_links:
        []
        # Example:
        # <name>: <link-url>

# footer info
footer:
    since: 20xx
    # Customize the server domain name ICP
    ICP:
        enable: false
        code:

#下边这句话原本打算设置摘要来着，但是发现有没有都没什么区别
# excerpt_description: true


# Gitalk
# https://github.com/gitalk/gitalk
gitalk:
    enable: true
    clientID: 8f4976e027fbda8dd147 # Default ClientID
    clientSecret: 23ec91414867398b1a88f6a1fd27167e5df5aa78  # Default ClientSecret
    repo: gitalk-comments # The name of repository of store comments
    owner: GuoShuaiGO # GitHub repo owner
    admin:  [GuoShuaiGO] # GitHub repo owner and collaborators, only these guys can initialize github issues
    language: zh-CN en # en, zh-CN, zh-TW, es-ES, fr, ru, de, pl and ko are currently available.
    proxy: # CORS proxy
    sites: # Sites
        []
        # Example:
        # <www.example.com>:
        #    clientID: <client-id>
        #    clientSecret: <client-secret>
